export type InputType =
  | "nickname"
  | "gender"
  | "description"
  | "referrer"
  | "uid"
  | "avatar"
  | "google-verification"
  | "phone"
  | "email"
  | "password"
  | "fund-pass"
  | "anti-phishing"
  | "activity"
  | undefined;
